/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.47
 * Generated at: 2019-12-06 07:24:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.signUp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class signUp_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/Users/donghyunkim/Desktop/RangProject/Rang/webapp/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/Users/donghyunkim/Desktop/RangProject/Rang/webapp/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1575616784000L));
    _jspx_dependants.put("jar:file:/Users/donghyunkim/Desktop/RangProject/Rang/webapp/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <title>회원가입</title>\n");
      out.write("    ");
      if (_jspx_meth_c_005fimport_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("    <link rel=\"stylesheet\" href=\"../../resources/css/singUp.css\">\n");
      out.write("    <script src=\"http://dmaps.daum.net/map_js_init/postcode.v2.js\"></script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\n");
      out.write("<section>\n");
      out.write("    <div class=\"container register\">\n");
      out.write("        <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/insert.me\" method=\"post\" enctype=\"multipart/form-data\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <!-- 왼쪽 화면 프로필 사진과 간단한 설명등 -->\n");
      out.write("                <div class=\"col-md-3 register-left\">\n");
      out.write("                    <div class=\"image-container\">\n");
      out.write("                        <img src=\"http://placehold.it/150x150\" id=\"imgProfile\" style=\"width: 150px; height: 150px\" class=\"img-thumbnail\" />\n");
      out.write("                        <div class=\"middle\">\n");
      out.write("                            <input type=\"button\" class=\"btn btn-secondary\" id=\"btnChangePicture\" value=\"사진 등록\">\n");
      out.write("                            <input type=\"file\" style=\"display: none;\" id=\"profilePicture\" name=\"pPhoto\">\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"ml-auto\">\n");
      out.write("                        <input type=\"button\" class=\"btn btn-primary d-none\" id=\"btnDiscard\" value=\"사진 제거\" />\n");
      out.write("                    </div>\n");
      out.write("                    <br>\n");
      out.write("                    <h3>환영합니다.</h3>\n");
      out.write("                    <p>간단한 설명</p>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"col-md-9 register-right\">\n");
      out.write("\n");
      out.write("                    <div class=\"tab-content\" id=\"myTabContent\">\n");
      out.write("                        <div class=\"tab-pane fade show active\" id=\"home\" role=\"tabpanel\" aria-labelledby=\"home-tab\">\n");
      out.write("                            <h3 class=\"register-heading\">회원가입</h3>\n");
      out.write("\n");
      out.write("                            <div class=\"row register-form\">\n");
      out.write("    ");
      out.write("\n");
      out.write("                                <div class=\"col-md-6\">\n");
      out.write("    ");
      out.write("\n");
      out.write("                                    <div class=\"form-group input-group\">\n");
      out.write("                                        <div class=\"input-group-prepend\">\n");
      out.write("                                            <span class=\"input-group-text\"> <i class=\"fa fa-envelope\"></i> </span>\n");
      out.write("                                        </div>\n");
      out.write("                                        <input name=\"email\" class=\"form-control\" placeholder=\"Email address\" type=\"text\">\n");
      out.write("                                    </div>\n");
      out.write("    ");
      out.write("\n");
      out.write("                                    <div class=\"form-group input-group\">\n");
      out.write("                                        <div class=\"input-group-prepend\">\n");
      out.write("                                            <span class=\"input-group-text\"> <i class=\"fa fa-user\"></i> </span>\n");
      out.write("                                        </div>\n");
      out.write("                                        <input name=\"userName\" class=\"form-control\" placeholder=\"Full name\" type=\"text\">\n");
      out.write("                                    </div>\n");
      out.write("    ");
      out.write("\n");
      out.write("                                    <div class=\"form-group input-group\">\n");
      out.write("                                        <div class=\"input-group-prepend\">\n");
      out.write("                                            <span class=\"input-group-text\"> <i class=\"fa fa-lock\"></i> </span>\n");
      out.write("                                        </div>\n");
      out.write("                                        <input name=\"password\" class=\"form-control\" placeholder=\"Create password\" type=\"password\">\n");
      out.write("                                    </div>\n");
      out.write("    ");
      out.write("\n");
      out.write("                                    <div class=\"form-group input-group\">\n");
      out.write("                                        <div class=\"input-group-prepend\">\n");
      out.write("                                            <span class=\"input-group-text\"> <i class=\"fa fa-lock\"></i> </span>\n");
      out.write("                                        </div>\n");
      out.write("                                        <input name=\"\" class=\"form-control\" placeholder=\"Repeat password\" type=\"password\">\n");
      out.write("                                    </div>\n");
      out.write("    ");
      out.write("\n");
      out.write("                                    <div class=\"form-group input-group\">\n");
      out.write("                                        <div class=\"input-group-prepend\">\n");
      out.write("                                            <span class=\"input-group-text\"><i class=\"fa fa-id-card\"></i> </span>\n");
      out.write("                                        </div>\n");
      out.write("                                        <input name=\"nickName\" class=\"form-control\" placeholder=\"Nick Name\" type=\"text\">\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("    ");
      out.write("\n");
      out.write("                                <div class=\"col-md-6\">\n");
      out.write("                                    ");
      out.write("\n");
      out.write("                                        <div class=\"form-group input-group\">\n");
      out.write("                                            <div class=\"input-group-prepend\">\n");
      out.write("                                                <span class=\"input-group-text\"><i class=\"fa fa-birthday-cake\"></i> </span>\n");
      out.write("                                            </div>\n");
      out.write("                                            <input name=\"birthDate\" class=\"form-control\" placeholder=\"생년월일 ex) 1990/04/03 \" type=\"text\">\n");
      out.write("                                        </div>\n");
      out.write("                                        ");
      out.write("\n");
      out.write("                                        <div class=\"form-group input-group\">\n");
      out.write("                                            <div class=\"input-group-prepend\">\n");
      out.write("                                                <span class=\"input-group-text\"> <i class=\"fa fa-map-marked-alt\"></i> </span>\n");
      out.write("                                            </div>\n");
      out.write("                                            <input id=\"zipCode\" name=\"zipCode\" class=\"form-control\" placeholder=\"zipCode\" type=\"text\">\n");
      out.write("                                            <button type=\"button\" style=\"margin: 0; padding: 0;\">\n");
      out.write("                                            <span class=\"input-group-text\"><i class=\"fas fa-search\" onclick=\"addrSearch()\"></i></span>\n");
      out.write("                                            </button>\n");
      out.write("                                        </div>\n");
      out.write("                                        ");
      out.write("\n");
      out.write("                                        <div class=\"form-group input-group\">\n");
      out.write("                                            <div class=\"input-group-prepend\">\n");
      out.write("                                                <span class=\"input-group-text\"> <i class=\"fa fa-map-marked-alt\"></i> </span>\n");
      out.write("                                            </div>\n");
      out.write("                                            <input id=\"address\" name=\"address\" class=\"form-control\" placeholder=\"address\" type=\"text\">\n");
      out.write("                                        </div>\n");
      out.write("                                        ");
      out.write("\n");
      out.write("                                        <div class=\"form-group input-group\">\n");
      out.write("                                            <div class=\"input-group-prepend\">\n");
      out.write("                                                <span class=\"input-group-text\"> <i class=\"fa fa-phone\"></i> </span>\n");
      out.write("                                            </div>\n");
      out.write("                                            <input name=\"phone\" class=\"form-control\" placeholder=\"Phone number\" type=\"text\">\n");
      out.write("                                        </div>\n");
      out.write("\n");
      out.write("    ");
      out.write("\n");
      out.write("    ");
      out.write("\n");
      out.write("    ");
      out.write("\n");
      out.write("    ");
      out.write("\n");
      out.write("    ");
      out.write("\n");
      out.write("    ");
      out.write("\n");
      out.write("    ");
      out.write("\n");
      out.write("    ");
      out.write("\n");
      out.write("                                    <input type=\"submit\" class=\"btnRegister\"  value=\"회원가입\"/>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </form>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- 이미지 관련 스크립트 -->\n");
      out.write("    <script>\n");
      out.write("        $(function () {\n");
      out.write("\n");
      out.write("            $imgSrc = $('#imgProfile').attr('src');\n");
      out.write("            <!-- 이미지 미리보기 스크립트 -->\n");
      out.write("            function readURL(input) {\n");
      out.write("\n");
      out.write("                if (input.files && input.files[0]) {\n");
      out.write("                    var reader = new FileReader();\n");
      out.write("\n");
      out.write("                    reader.onload = function (e) {\n");
      out.write("                        $('#imgProfile').attr('src', e.target.result);\n");
      out.write("                    };\n");
      out.write("\n");
      out.write("                    reader.readAsDataURL(input.files[0]);\n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            <!--  -->\n");
      out.write("            $('#btnChangePicture').on('click', function () {\n");
      out.write("                if (!$('#btnChangePicture').hasClass('changing')) {\n");
      out.write("                    $('#profilePicture').click();\n");
      out.write("                }\n");
      out.write("                // else {\n");
      out.write("                //     // change\n");
      out.write("                // }\n");
      out.write("            });\n");
      out.write("\n");
      out.write("            $('#profilePicture').on('change', function () {\n");
      out.write("                readURL(this);\n");
      out.write("                $('#btnChangePicture').addClass('changing');\n");
      out.write("                $('#btnChangePicture').attr('value', '등록 완료');\n");
      out.write("                $('#btnDiscard').removeClass('d-none');\n");
      out.write("                // $('#imgProfile').attr('src', '');\n");
      out.write("            });\n");
      out.write("            $('#btnDiscard').on('click', function () {\n");
      out.write("                // if ($('#btnDiscard').hasClass('d-none')) {\n");
      out.write("                $('#btnChangePicture').removeClass('changing');\n");
      out.write("                $('#btnChangePicture').attr('value', 'Change');\n");
      out.write("                $('#btnDiscard').addClass('d-none');\n");
      out.write("                $('#imgProfile').attr('src', $imgSrc);\n");
      out.write("                $('#profilePicture').val('');\n");
      out.write("                // }\n");
      out.write("            });\n");
      out.write("        });\n");
      out.write("    </script>\n");
      out.write("\n");
      out.write("    <!-- 다음 주소 Api -->\n");
      out.write("    <script>\n");
      out.write("        // 우편번호 검색\n");
      out.write("        function addrSearch() {\n");
      out.write("            new daum.Postcode({\n");
      out.write("                oncomplete: function(data) {\n");
      out.write("                    // 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.\n");
      out.write("\n");
      out.write("                    // 각 주소의 노출 규칙에 따라 주소를 조합한다.\n");
      out.write("                    // 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.\n");
      out.write("                    var fullAddr = ''; // 최종 주소 변수\n");
      out.write("                    var extraAddr = ''; // 조합형 주소 변수\n");
      out.write("\n");
      out.write("                    // 사용자가 선택한 주소 타입에 따라 해당 주소 값을 가져온다.\n");
      out.write("                    if (data.userSelectedType === 'R') { // 사용자가 도로명 주소를 선택했을 경우\n");
      out.write("                        fullAddr = data.roadAddress;\n");
      out.write("\n");
      out.write("                    } else { // 사용자가 지번 주소를 선택했을 경우(J)\n");
      out.write("                        fullAddr = data.jibunAddress;\n");
      out.write("                    }\n");
      out.write("\n");
      out.write("                    // 사용자가 선택한 주소가 도로명 타입일때 조합한다.\n");
      out.write("                    if(data.userSelectedType === 'R'){\n");
      out.write("                        //법정동명이 있을 경우 추가한다.\n");
      out.write("                        if(data.bname !== ''){\n");
      out.write("                            extraAddr += data.bname;\n");
      out.write("                        }\n");
      out.write("                        // 건물명이 있을 경우 추가한다.\n");
      out.write("                        if(data.buildingName !== ''){\n");
      out.write("                            extraAddr += (extraAddr !== '' ? ', ' + data.buildingName : data.buildingName);\n");
      out.write("                        }\n");
      out.write("                        // 조합형주소의 유무에 따라 양쪽에 괄호를 추가하여 최종 주소를 만든다.\n");
      out.write("                        fullAddr += (extraAddr !== '' ? ' ('+ extraAddr +')' : '');\n");
      out.write("                    }\n");
      out.write("\n");
      out.write("                    // 우편번호와 주소 정보를 해당 필드에 넣는다.\n");
      out.write("                    $('#zipCode').val(data.zonecode); //5자리 새우편번호 사용\n");
      out.write("\n");
      out.write("                    $('#address').val(fullAddr);\n");
      out.write("\n");
      out.write("                    // 커서를 상세주소 필드로 이동한다.\n");
      out.write("                    // $('#address2').focus();\n");
      out.write("                }\n");
      out.write("            }).open();\n");
      out.write("        }\n");
      out.write("    </script>\n");
      out.write("</section>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<script src=\"../../resources/js/scroll.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fimport_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f0 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f0_reused = false;
    try {
      _jspx_th_c_005fimport_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f0.setParent(null);
      // /views/signUp/signUp.jsp(8,4) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f0.setUrl("../common/commonUtil.jsp");
      int[] _jspx_push_body_count_c_005fimport_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f0 = _jspx_th_c_005fimport_005f0.doStartTag();
        if (_jspx_th_c_005fimport_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f0);
      _jspx_th_c_005fimport_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f0_reused);
    }
    return false;
  }
}
